#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, sorted by occurrences (greatest to lowest)
awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -rn
