#!/usr/bin/env bash
# This script displays the content of the current directory in list format, showing only the part after the first dash
shopt -s nullglob
for file in $(ls); do
    if [[ "$file" == *-* ]]; then
        echo "${file#*-}"
    fi
done
