#!/usr/bin/env bash
# Init script that starts, stops, or restarts manage_my_process
DIR="$(dirname "$0")"
PIDFILE="/var/run/my_process.pid"

case "$1" in
  start)
    "$DIR"/manage_my_process &
    echo $! > "$PIDFILE"
    echo "manage_my_process started"
    ;;
  stop)
    kill -9 "$(cat "$PIDFILE")" 2> /dev/null
    rm -f "$PIDFILE"
    echo "manage_my_process stopped"
    ;;
  restart)
    kill -9 "$(cat "$PIDFILE")" 2> /dev/null
    rm -f "$PIDFILE"
    "$DIR"/manage_my_process &
    echo $! > "$PIDFILE"
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
